name: Node CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: npm

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

  publish:
    needs: build
    runs-on: ubuntu-latest
    environment: npm

    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm set //registry.npmjs.org/:_authToken='${NODE_AUTH_TOKEN}'
    # - run: npm version patch - TODO: Need to provide github identity for this to succeed
    - run: echo ${NODE_AUTH_TOKEN}
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
